story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
]

story4/urls.py
from django.urls import path
from . import views

app_name = 'story4'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('schedule/', views.schedule, name='schedule'),
    path('schedule/create', views.schedule_create, name='schedule_create'),
    path('schedule/delete', views.schedule_delete, name='schedule_delete'),

]

story4/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Schedule(models.Model):

    activity = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    time = models.TimeField()
    place = models.CharField(max_length=20)
    category = models.CharField(max_length=20)

    def __str__(self):
        return self.activity

story4/forms.py
from django import forms
from .models import Schedule


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['activity', 'date', 'time', 'place', 'category']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

story4/views.py
from django.shortcuts import render, redirect
from .models import Schedule
from . import forms

# Create your views here.
def about(request):
    return render(request, 'story3a.html')

def home(request):
    return render(request, 'story3h.html')

def profile(request):
    return render(request, 'story3p.html')

def schedule(request):
    schedules = Schedule.objects.all().order_by('date')
    return render(request, 'schedule.html', {'schedules': schedules})

def schedule_create(request):
    if request.method == 'POST':
        form = forms.ScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story4:schedule')

    else:
        form = forms.ScheduleForm()
    return render(request, 'schedule_create.html', {'form': form})

def schedule_delete(request):
	Schedule.objects.all().delete()
	return render(request, "schedule.html")

story4/templates/navbar.html
{% load static %}
<html lang="en">
<head>

    

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css:style.css' %}">
</head>
<body  style="background-color: #DEE0E3">
    
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #4a4a48">
  <a class="navbar-brand" href="{% url 'story4:home'%}">
  <img src="{% static 'images/logo.jpg' %}" alt="Logo" style="width:40px; height:40px;"></a>
  <button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse" data-target="#navb" aria-expanded="false">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse collapse" id="navb" style="">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story4:profile'%}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story4:about'%}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href={% url 'story4:schedule' %}>Schedule</a>
      </li>
      <a class="nav-link" href="https://drive.google.com/open?id=1VyJE_jKOuUTUZSTksB8AWB4tL2wNsbk3">CV</a>
      </li>
    </ul>
  </div>
</nav>

{% block content %}
{% endblock %}

</body>

story4/templates/schedule.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}

<head>

  <title> Fathur | Schedule </title>
    

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css:style.css' %}">
</head>
    
<div class="container mt-3" style="margin: 0 7% 0 7%">
<h1>SCHEDULE</h1>
    <div class="article">
        <a href="{% url 'story4:schedule' %}"></a>
        <div class="article">
            <div class="row">
                {% for schedule in schedules %}
                    <div class="col-sm-4 text-center">
                        <h2>{{ schedule.activity }}</h2>
                        <p>{{ schedule.date.date }}</p>
                        <p>{{ schedule.time}}</p>
                        <p>{{ schedule.place }}</p>
                        <p>{{ schedule.category }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class = 'col-md-12'>
        <div class = 'form-group'>
            <a href="{% url 'story4:schedule_delete' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm">Clear</button></a>
            <a href="{% url 'story4:schedule_create' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm">Create</button></a>
    </div>
</div>
{% endblock %}

story4/templates/schedule_create.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}
<head>

  <title> Fathur | Schedule </title>
    

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css:style.css' %}">
</head>
<form class="css" action="{% url 'story4:schedule_create' %}" method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                {% for fields in form %}
                    {{ fields.label_tag }}
                    <br>
                    {{ fields }}
                {% endfor %}
            </div>
        </div>
        <div class="form-row">
            <div class="col-sm-1"></div>
            <input type="submit" class="btn btn-primary float-right" value="Add">
        </form>
    {% endblock %}

story4/templates/story3a.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
{% block content %}

<head>

  <title> Fathur | About </title>
    

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css:style.css' %}">
</head>

    
<div class="container mt-3" style="margin: 0 7% 0 7%">
<h1>About</h1>
<div style="background-color:#827F7F; color: white;margin:5% 7% 5% 7%; padding:2% 4% 2% 4% ">
    <div class="row">
    <p style="padding-top:15px;font-size: 20px;">Nama saya Fathur Rahman Prawira, mahasiswa 
Fakultas Ilmu Komputer Universitas Indonesia.
Saya lahir di Padang pada tanggal 13 November 2000, 
lalu dibesarkan di Surabaya dan Jakarta. Saya anak
kedua dari dua bersaudara. Jarak antara saya
dengan kakak saya sekitar 5 tahun. Tujuan saya
melanjutkan pendidikan saya ke Fasilkom agar saya
dapat mengenal IT lebih dalam.</p>

    </div>
</div>
</div>

<div style="background-color:#827F7F; color: white;margin:40% 10% 9% 10%; padding:2% 4% 2% 4% ">
     <h1 style="font-size: 25px;font-style: italic;">Contact</h1>
    <div class="row">
    <p>Alamat Rumah: Regensi Melati Mas 2 Blok C7/2 Jelupang, Serpong Utara, Tangerang Selatan 15323
    <br>Alamat Kos: Griya Zayda, Jalan Haji Amat 1 No. 17A, 
    Kukusan, Beji, Depok<br>Phone: +6282237000699 <br>E-mail: fathurrahmanprawira86@gmail.com </p>
  

{% endblock %}

story4/templates/story3h.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

  <title> Fathur | Home </title>
    

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css:style.css' %}">
<style>
body, html {
  height: 100%;
  margin: 0;
}

.bg {
  
  background-image: url("{% static 'image/marble-white-1-2018.jpg' %}");

  
  width: 1517px;
  height: 1024px;
  
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
</style>

</head>
<body>

<div class="bg"></div>
<div class="container">
<p style="position: absolute;
width: 259px;
height: 54px;
left: 608px;
top: 131px;font-weight: bold; font-size: 48px;">Välkommen</p>
<p style="font-weight: bold;position: absolute;
width: 437px;
height: 65px;
left: 262px;
top: 195px;">
добро пожаловать </p>
<p style="font-weight: bold;position: absolute;
width: 254px;font-size: 48px;
height: 88px;
left: 820px;
top: 216px;">Velkommen</p>
<p style="font-weight: bold;font-size: 48px;position: absolute;
width: 249px;
height: 61px;
left: 405px;
top: 290px;">Bienvenue</p>
<p style="font-weight: bold;font-size: 48px;position: absolute;
width: 246px;
height: 88px;
left: 759px;
top: 277px;">Benvenuto</p>
<p style="font-weight: bold;font-size: 48px;position: absolute;
width: 219px;
height: 88px;
left: 309px;
top: 363px;
">迎接</p>
<p style="font-weight: bold;position: absolute;
width: 219px;font-size: 48px;
height: 88px;
left: 519px;
top: 353px;">WELCOME</p>
<p style="font-weight: bold;position: absolute;
width: 219px;font-size: 48px;
height: 88px;
left: 882px;
top: 353px;">歓迎歓迎</p>
<p style="font-weight: bold;position: absolute;
width: 219px;
height: 88px;font-size: 48px;
left: 348px;
top: 432px;">Welkom</p>
<p style="font-weight: bold;position: absolute;
width: 270px;
height: 88px;font-size: 48px;
left: 637px;
top: 432px;">Willkommen</p>
<p style="font-weight: bold;position: absolute;
width: 219px;
height: 88px;font-size: 48px;
left: 1005px;
top: 459px;
">Croeso</p>
<p style="font-weight: bold;position: absolute;
width: 383px;
height: 88px;font-size: 48px;
left: 389px;
top: 513px;">Selamat Datang</p>
<p style="font-weight: bold;position: absolute;
width: 420px;font-size: 38px;
height: 88px;
left: 782px;
top: 557px;
">Wilujeung Sumping</p>
<p style="position: absolute;
width: 209px;font-weight: bold;
font-size: 20px;
height: 54px;
left: 615px;
top: 726px;">Let's take a tour</p>
<a class="nav-link" href="{% url 'story4:profile'%}" style="position: absolute;
width: 209px;
height: 54px;
left: 348px;
top: 803px;
">Profile</a>
<a class="nav-link" href="{% url 'story4:about'%}" style="position: absolute;
width: 209px;
height: 54px;
left: 673px;
top: 829px;">About</a>
<a class="nav-link" style="position: absolute;
width: 209px;
height: 54px;
left: 998px;
top: 811px;" href="https://drive.google.com/open?id=1VyJE_jKOuUTUZSTksB8AWB4tL2wNsbk3">CV</a>
</div>
</body>
</html>

story4/templates/story3p.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
{% block content %}

<head>

  <title> Fathur | Profile </title>
    

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css:style.css' %}">
</head>

<div class="container mt-3" style="margin: 0 4% 0 4%">
  <h1>Profile</h1>
  <div class="media border p-3"style="background-color: #827F7F;color: white;">
    <img src="{% static 'images/S_8354606108989.jpg' %}" alt="Fathur" class="mr-3 mt-3 rounded-circle" style="width:110px;">
    <div class="media-body" >
      <p style="padding-top:15px;">Fathur Rahman Prawira</p>
      <p>Undergraduate Student at Computer Science - Universitas Indonesia</p>
      <p style="padding-bottom:15px;"><small>“Your time is limited, so don’t waste it living someone else’s life.” - Steve Jobs</small></p>      
    </div>
  </div>
</div>


  <div style="background-color:#827F7F; color: white;margin:7% 10% 5% 10%; padding:2% 4% 2% 4% ">
     <h1 style="font-size: 27px;font-style: italic;">Experience</h1>
    <div class="row">
   
      <div class="col-md-2">
        <img src="{% static 'images/hsc.jpg' %}" alt="HSC" class="mr-3 mt-3 rounded-circle" style="width:80px;">
      </div>
      <div class="col-md-10">
        <p style="padding-top:15px;">High School Celebration 2017 </p>
        <p>Vice Person In Charge Sponsorship</p>
        <p style="padding-bottom:15px;">Jan 2017 - Sep 2017</p>      

      </div>
      
    </div>
    <div class="row">
     <div class="col-md-2">
        <img src="{% static 'images/cgt.png' %}" alt="CGT" class="mr-3 mt-3 rounded-circle" style="width:80px;">
      </div>
      <div class="col-md-10">
        <p style="padding-top:15px;">Computers Get Together 2019</p>
        <p>HRD Sponsorship</p>
        <p style="padding-bottom:15px;">Jan 2019 - Apr 2019</p>      

      </div>
 
    </div>
        <div class="row">
      <div class="col-md-2">
        <img src="{% static 'images/bem.png' %}" alt="BEM" class="mr-3 mt-3 rounded-circle" style="width:80px;">
      </div>
      <div class="col-md-10">
        <p style="padding-top:15px;">BEM Fakultas Ilmu Komputer UI</p>
        <p>Staff Art and Culture</p>
        <p style="padding-bottom:15px;">Feb 2019 - Present</p>      

      </div>
 
    </div>
    <div class="row">
     <div class="col-md-2">
        <img src="{% static 'images/cf.jpg' %}" alt="COMPFEST" class="mr-3 mt-3 rounded-circle" style="width:80px;">
      </div>
      <div class="col-md-10">
        <p style="padding-top:15px;">COMPFEST</p>
        <p>Staff Transportation and Venue</p>
        <p style="padding-bottom:15px;">Jan 2019 - Present</p>      

      </div>
 
    </div>
    
  </div>

  <div style="background-color:#827F7F; color: white;margin:5% 10% 9% 10%; padding:2% 4% 2% 4% ">
     <h1 style="font-size: 27px;font-style: italic;">Education</h1>
    <div class="row">
   
      <div class="col-md-2">
        <img src="{% static 'images/LOGO SMPN 19 JAKARTA.jpg' %}" alt="smp 19" class="mr-3 mt-3 rounded-circle" style="width:80px;">
      </div>
      <div class="col-md-10">
        <p style="padding-top:15px;">SMP Negeri 19 Jakarta</p>
        <p>Junior High School</p>
        <p style="padding-bottom:15px;">Jun 2012 - May 2015</p>      

      </div>
      
    </div>
    <div class="row">
     <div class="col-md-2">
        <img src="{% static 'images/LOGO-SMAN-34-JAKARTA.jpg' %}" alt="sman 34" class="mr-3 mt-3 rounded-circle" style="width:80px;">
      </div>
      <div class="col-md-10">
        <p style="padding-top:15px;">SMA Negeri 34 Jakarta</p>
        <p>High School, Natural Science</p>
        <p style="padding-bottom:15px;">Jun 2015 - Apr 2018</p>      

      </div>
 
    </div>
        <div class="row">
     <div class="col-md-2">
        <img src="{% static 'images/makara.png' %}" alt="UI" class="mr-3 mt-3 rounded-circle" style="width:80px;">
      </div>
      <div class="col-md-10">
        <p style="padding-top:15px;">Universitas Indonesia</p>
        <p>Undergraduate, Computer Science</p>
        <p style="padding-bottom:15px;">May 2018 - Present</p>      

      </div>
 
    </div>
  </div>

  <div style="background-color:#827F7F; color: white;margin:5% 10% 9% 10%; padding:2% 4% 2% 4% ">
     <h1 style="font-size: 27px;font-style: italic;">Skills</h1>
    <div class="row">  
      <div class="col-md-12">
        <div class="progress" style="margin: 2% 0 2% 0;">
          <div class="progress-bar" role="progressbar" style="width: 68%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">Java</div>
        </div>
        <div class="progress" style="margin: 2% 0 2% 0;">
          <div class="progress-bar" role="progressbar" style="width: 75%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">Python</div>
        </div>
        <div class="progress"style="margin: 2% 0 2% 0;">
          <div class="progress-bar" role="progressbar" style="width: 40%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">CSS</div>
        </div>
        <div class="progress"style="margin: 2% 0 2% 0;">
          <div class="progress-bar" role="progressbar" style="width: 52%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">HTML</div>
        </div>
        <div class="progress"style="margin: 2% 0 2% 0;">
          <div class="progress-bar" role="progressbar" style="width: 82%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">Microsoft Office</div>
        </div>

      </div>
    </div>
  </div>

  <div>
    <div class="row" style="margin: 0 35% 0 35%">
      <a class="nav-link" href="https://facebook.com/fathur.rahman.prawira/">
      <img src="{% static 'images/fb.png' %}"  alt="facebook" style="width:90px;">
      </a>
      <a class="nav-link" href="https://twitter.com/fathurrpp/">
      <img src="{% static 'images/twitter.png' %}" alt="twiter" style="width:70px;">
      </a>
      <a class="nav-link" href="https://instagram.com/fathurrp/">
      <img src="{% static 'images/ig.png' %}" alt="instagram" style="width:70px;">
      </a>
      <a class="nav-link" href="https://www.linkedin.com/in/fathurrahmanprawira/">
      <img src="{% static 'images/li.png' %}" alt="linkedin" style="width:70px;">
      </a>
    </div>
  </div>

{% endblock %}